debug: false

server:
  port: 9090
#  session:
#    session timeout one day
#    timeout: 86400

security:
  user:
    name: max
    password: muster

zuul: 
  sensitiveHeaders: 
  routes:
    auth: 
      path: /auth/**
      url: http://localhost:8090
    
    api: 
      path: /api/**
      url: http://localhost:8100
    

 
ribbon:
   eureka:
     enabled: false

logging:
  level:
    org.springframework.security: INFO