debug: false

server:
  port: 9090

security:
  user:
    name: max
    password: muster

zuul: 
  routes:
    ui: /**
    api: /api/**
    
 #   book:
 #    path: /**
 #    url: http://localhost:8080	
 
ribbon:
   eureka:
     enabled: false

logging:
  level:
    org.springframework.security: INFO